version: "3.3"
services:
  reader:
    build:
      context: .
      dockerfile: "./Dockerfile.development"
    container_name: golang
    stdin_open: true
    tty: true
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2.00'
          # memory: 50M
        reservations:
          cpus: '2.00'
          # memory: 20M
    volumes:
      - ./src:/go/src/log-reader-go
      - ./.vscode:/go/src/log-reader-go
      - ./data:/var/log/log-reader-go
