version: "3.3"
services:
  elastic:
    image: elasticsearch:8.8.0
    container_name: reader-elastic
    stdin_open: true
    tty: true
    restart: always
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - http.host=0.0.0.0
      - node.name=es01
      - cluster.name=es-docker-cluster
      - ELASTICSEARCH_HOSTS=http://0.0.0.0:9200
      - ELASTICSEARCH_USER=elastic
      - ELASTICSEARCH_PASSWORD=elastic123
      - STACK_VERSION=8.8.0
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - reader-network
  reader:
    build:
      context: .
      dockerfile: "./go.Dockerfile"
    container_name: reader-go
    stdin_open: true
    tty: true
    restart: on-failure
    env_file:
      - .env
    networks:
      - reader-network
    volumes:
      - ./src:/go/src/log-reader-go
      - ./.vscode:/go/src/log-reader-go
      - ./data/log-reader-go:/var/log/log-reader-go
      - ./data/elasticsearch:/var/log/elasticsearch

volumes:
  esdata1:
    driver: local

networks:
  reader-network:
    driver: bridge
