FROM golang:1.20.3-alpine

ARG user=lucas
ARG uid=1000

WORKDIR /go/src/log-reader-go

RUN apk add --no-cache \
    bash

RUN adduser -D -u 1000 -s /bin/bash ${user}

USER ${user}

ENV HOME /home/${user}